'use client'
import Link from 'next/link'
import { useMemo, useState } from 'react'
import type { LabOrder } from '@/lib/labTypes'
import { labLabel, labStatusClass } from '@/lib/labTypes'

export default function LabOrderDirectory({ orders }: { orders: LabOrder[] }) {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('all')
  const filtered = useMemo(() => orders.filter(order => `${order.id} ${order.patient_name} ${order.doctor_name} ${order.items.map(x => x.test_name).join(' ')}`.toLowerCase().includes(search.toLowerCase()) && (status === 'all' || order.status === status)), [orders, search, status])
  return <div className="space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-blue-600">Authorized laboratory queue</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Lab Orders</h1><p className="mt-1 text-slate-600">Accept unassigned work and follow only the guarded laboratory sequence.</p></div><div className="grid gap-3 rounded-2xl border bg-white p-4 shadow-sm md:grid-cols-3"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search order, patient, doctor, or test" className="md:col-span-2 rounded-xl border border-slate-300 px-4 py-3"/><select value={status} onChange={e => setStatus(e.target.value)} className="rounded-xl border border-slate-300 bg-white px-4 py-3"><option value="all">All statuses</option><option value="ordered">Ordered</option><option value="sample_collected">Sample collected</option><option value="processing">Processing</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div><section className="overflow-hidden rounded-2xl border bg-white shadow-sm">{filtered.length === 0 ? <p className="p-10 text-center text-slate-500">No authorized lab orders found.</p> : <div className="overflow-x-auto"><table className="min-w-full divide-y text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-4">Order / date</th><th className="px-4 py-4">Patient</th><th className="px-4 py-4">Doctor</th><th className="px-4 py-4">Tests</th><th className="px-4 py-4">Priority</th><th className="px-4 py-4">Status</th><th className="px-4 py-4">Action</th></tr></thead><tbody className="divide-y">{filtered.map(order => <tr key={order.id}><td className="px-4 py-4"><p className="font-semibold">#{order.id}</p><p className="text-xs text-slate-500">{new Date(order.ordered_at).toLocaleString()}</p></td><td className="px-4 py-4">{order.patient_name}</td><td className="px-4 py-4">{order.doctor_name}</td><td className="px-4 py-4">{order.items.map(x => x.test_name).join(', ')}</td><td className="px-4 py-4"><span className={`rounded-full px-2 py-0.5 text-xs font-semibold capitalize ring-1 ring-inset ${labStatusClass(order.priority)}`}>{order.priority}</span></td><td className="px-4 py-4"><span className={`rounded-full px-2 py-0.5 text-xs font-semibold capitalize ring-1 ring-inset ${labStatusClass(order.status)}`}>{labLabel(order.status)}</span></td><td className="px-4 py-4"><Link href={`/lab/orders/${order.id}`} className="font-semibold text-blue-700">Open</Link></td></tr>)}</tbody></table></div>}</section></div>
}
