'use client'
import { useState } from 'react'
import { addInventoryAction, adjustInventoryAction, createCategoryAction, createMedicineAction, createSupplierAction } from '@/app/actions/pharmacist'
import SubmitButton from '@/components/SubmitButton'
import type { InventoryBatch, Medicine, MedicineCategory, Supplier } from '@/lib/pharmacistTypes'
import { pharmacyStatusClass, pharmacyStatusLabel } from '@/lib/pharmacistTypes'

const input = 'mt-1 w-full rounded-xl border border-slate-300 bg-white p-3'
export default function InventoryWorkspace({ inventory, medicines, categories, suppliers }: { inventory: InventoryBatch[]; medicines: Medicine[]; categories: MedicineCategory[]; suppliers: Supplier[] }) {
  const [notice, setNotice] = useState('')
  const [error, setError] = useState('')
  async function run(action: (data: FormData) => Promise<{success?: boolean; error?: string}>, data: FormData, message: string) {
    setNotice(''); setError('')
    const response = await action(data)
    if (response.error) setError(response.error); else setNotice(message)
  }
  return <div className="space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-blue-600">Batch-controlled stock</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Medicine Inventory</h1><p className="mt-1 text-slate-600">Manage medicine codes, suppliers, batches, expiry, and audited stock adjustments.</p></div>{error && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{notice && <p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{notice}</p>}
    <div className="grid gap-4 xl:grid-cols-2"><details className="rounded-2xl border bg-white p-5 shadow-sm"><summary className="cursor-pointer font-semibold">Set up category, supplier, or medicine</summary><div className="mt-5 grid gap-5 md:grid-cols-2"><form action={data => run(createCategoryAction, data, 'Category created.')} className="space-y-3"><h3 className="font-semibold">Category</h3><label className="text-sm">Name<input name="name" required maxLength={100} className={input}/></label><label className="text-sm">Description<input name="description" maxLength={500} className={input}/></label><SubmitButton className="rounded-xl border border-blue-300 px-4 py-2 font-semibold text-blue-700">Add category</SubmitButton></form><form action={data => run(createSupplierAction, data, 'Supplier created.')} className="space-y-3"><h3 className="font-semibold">Supplier</h3><label className="text-sm">Name<input name="name" required maxLength={150} className={input}/></label><label className="text-sm">Contact person<input name="contact_person" maxLength={100} className={input}/></label><SubmitButton className="rounded-xl border border-blue-300 px-4 py-2 font-semibold text-blue-700">Add supplier</SubmitButton></form></div><form action={data => run(createMedicineAction, data, 'Medicine created.')} className="mt-6 grid gap-3 md:grid-cols-3"><label className="text-sm">Medicine name<input name="name" required maxLength={150} className={input}/></label><label className="text-sm">SKU / code<input name="sku" maxLength={100} className={input}/></label><label className="text-sm">Generic name<input name="generic_name" maxLength={150} className={input}/></label><label className="text-sm">Category<select name="category_id" required className={input}><option value="">Select</option>{categories.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-sm">Unit<input name="unit" placeholder="tablet, bottle..." className={input}/></label><div className="flex items-end"><SubmitButton className="w-full rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white">Add medicine</SubmitButton></div></form></details>
      <details open className="rounded-2xl border bg-white p-5 shadow-sm"><summary className="cursor-pointer font-semibold">Add stock batch</summary><form action={data => run(addInventoryAction, data, 'Stock batch added.')} className="mt-5 grid gap-3 md:grid-cols-2"><label className="text-sm">Medicine<select name="medicine_id" required className={input}><option value="">Select</option>{medicines.filter(x => x.status === 'active').map(x => <option key={x.id} value={x.id}>{x.name} {x.sku ? `(${x.sku})` : ''}</option>)}</select></label><label className="text-sm">Supplier<select name="supplier_id" className={input}><option value="">Not specified</option>{suppliers.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-sm">Batch number<input name="batch_number" required maxLength={100} className={input}/></label><label className="text-sm">Expiry date<input name="expiry_date" type="date" required className={input}/></label><label className="text-sm">Quantity<input name="quantity" type="number" min="1" required className={input}/></label><label className="text-sm">Purchase price<input name="purchase_price" type="number" min="0" step="0.01" required className={input}/></label><label className="text-sm">Selling price<input name="selling_price" type="number" min="0" step="0.01" required className={input}/></label><div className="flex items-end"><SubmitButton className="w-full rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white">Add stock</SubmitButton></div></form></details></div>
    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm">{inventory.length === 0 ? <p className="p-10 text-center text-slate-500">No inventory has been created.</p> : <div className="overflow-x-auto"><table className="min-w-full divide-y text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-4">Medicine</th><th className="px-4 py-4">Batch / supplier</th><th className="px-4 py-4">Expiry</th><th className="px-4 py-4">Stock</th><th className="px-4 py-4">Audited adjustment</th></tr></thead><tbody className="divide-y">{inventory.map(batch => <tr key={batch.id}><td className="px-4 py-4"><p className="font-semibold">{batch.medicine_name}</p><p className="text-xs text-slate-500">{batch.sku || 'No SKU'}</p></td><td className="px-4 py-4"><p>{batch.batch_number}</p><p className="text-xs text-slate-500">{batch.supplier_name || 'Supplier not specified'}</p></td><td className="px-4 py-4">{batch.expiry_date}</td><td className="px-4 py-4"><p className="font-semibold">{batch.available_quantity} / {batch.quantity}</p><span className={`mt-1 inline-flex rounded-full px-2 py-0.5 text-xs font-semibold capitalize ring-1 ring-inset ${pharmacyStatusClass(batch.stock_status)}`}>{pharmacyStatusLabel(batch.stock_status)}</span></td><td className="px-4 py-4"><form action={data => run(adjustInventoryAction, data, 'Stock adjustment recorded.')} className="flex min-w-[430px] gap-2"><input type="hidden" name="batch_id" value={batch.id}/><select name="action" className="rounded-lg border px-2"><option value="add_stock">Add stock</option><option value="update_stock">Update counted stock</option><option value="expired">Record expired</option><option value="damaged">Record damaged</option></select><input name="quantity" type="number" min="1" required placeholder="Qty" className="w-20 rounded-lg border px-2"/><input name="reason" maxLength={255} placeholder="Reason" className="w-32 rounded-lg border px-2"/><SubmitButton className="rounded-lg bg-slate-900 px-3 py-2 font-semibold text-white">Record</SubmitButton></form></td></tr>)}</tbody></table></div>}</section>
  </div>
}
