'use client'
import Link from 'next/link'
import { useState } from 'react'
import { acceptLabOrderAction, collectLabSampleAction, enterLabResultAction, finalizeLabResultAction, startLabProcessingAction } from '@/app/actions/lab'
import SubmitButton from '@/components/SubmitButton'
import type { LabActionResult } from '@/app/actions/lab'
import type { LabOrder } from '@/lib/labTypes'
import { labLabel, labStatusClass } from '@/lib/labTypes'

const field = 'mt-1 w-full rounded-xl border border-slate-300 p-3'
export default function LabOrderWorkflow({ order }: { order: LabOrder }) {
  const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  async function run(action: (data: FormData) => Promise<LabActionResult>, data: FormData, message: string) { setError(''); setNotice(''); const result = await action(data); if (result.error) setError(result.error); else setNotice(message) }
  return <div className="space-y-4">{error && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{notice && <p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{notice}</p>}{order.assigned_technician_id === null && order.status !== 'cancelled' && <section className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><h2 className="font-semibold text-blue-950">Accept this order</h2><p className="mt-1 text-sm text-blue-800">Accepting assigns every requested test to you. Other technicians will no longer see or modify this order.</p><form action={data => run(acceptLabOrderAction, data, 'Order accepted.')} className="mt-4"><input type="hidden" name="order_id" value={order.id}/><SubmitButton className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Accept order</SubmitButton></form></section>}
    {order.items.map(item => <section key={item.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{item.test_code || `Test #${item.test_id}`}</p><h2 className="mt-1 text-xl font-semibold">{item.test_name}</h2></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ring-1 ring-inset ${labStatusClass(item.status)}`}>{labLabel(item.status)}</span></div>
      {order.assigned_technician_id === null && <p className="mt-4 text-sm text-slate-500">Accept the order to begin sample processing.</p>}
      {order.assigned_technician_id !== null && item.status === 'ordered' && <form action={data => run(collectLabSampleAction, data, 'Sample collection recorded.')} className="mt-5 grid gap-3 md:grid-cols-3"><input type="hidden" name="order_id" value={order.id}/><input type="hidden" name="order_item_id" value={item.id}/><label className="text-sm font-medium">Sample type<input name="sample_type" maxLength={100} placeholder="Blood, urine, swab..." className={field}/></label><label className="text-sm font-medium">Barcode<input name="barcode" required maxLength={100} className={field}/></label><div className="flex items-end"><SubmitButton className="w-full rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white">Record sample collection</SubmitButton></div></form>}
      {item.status === 'sample_collected' && <div className="mt-5"><p className="text-sm text-slate-600">Sample: {item.sample?.sample_type || 'Not specified'} · Barcode {item.sample?.barcode}</p><form action={data => run(startLabProcessingAction, data, 'Test processing started.')} className="mt-3"><input type="hidden" name="order_id" value={order.id}/><input type="hidden" name="order_item_id" value={item.id}/><SubmitButton className="rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white">Start processing</SubmitButton></form></div>}
      {item.status === 'processing' && !item.result && <form action={data => run(enterLabResultAction, data, 'Draft result entered.')} className="mt-5 grid gap-3 md:grid-cols-2"><input type="hidden" name="order_id" value={order.id}/><input type="hidden" name="order_item_id" value={item.id}/><label className="text-sm font-medium md:col-span-2">Test result<textarea name="result_value" rows={3} maxLength={5000} className={field}/></label><label className="text-sm font-medium">Numeric value<input name="numeric_value" type="number" step="any" className={field}/></label><label className="text-sm font-medium">Unit<input name="unit" maxLength={50} className={field}/></label><label className="text-sm font-medium">Reference range<input name="reference_range" maxLength={100} className={field}/></label><label className="text-sm font-medium">Technician notes<input name="remarks" maxLength={2000} className={field}/></label><p className="text-xs text-slate-500">Enter text or a numeric result. This remains editable as a draft.</p><SubmitButton className="rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white">Enter draft result</SubmitButton></form>}
      {item.result?.status === 'draft' && <div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="font-semibold text-amber-900">Draft result entered</p><p className="mt-1 text-sm text-amber-800">{item.result.result_value || item.result.numeric_value} {item.result.unit || ''}</p><div className="mt-3 flex gap-2"><Link href="/lab/results" className="rounded-lg border border-amber-400 px-3 py-2 text-sm font-semibold text-amber-900">Edit draft</Link><form action={data => run(finalizeLabResultAction, data, 'Result finalized.')}><input type="hidden" name="order_id" value={order.id}/><input type="hidden" name="result_id" value={item.result.id}/><SubmitButton className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white">Complete & finalize</SubmitButton></form></div></div>}
      {item.result?.status === 'finalized' && <div className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-900"><p className="font-semibold">Finalized result</p><p className="mt-1">{item.result.result_value || item.result.numeric_value} {item.result.unit || ''}</p><p className="mt-2 text-xs">Finalized {item.result.finalized_at ? new Date(item.result.finalized_at).toLocaleString() : ''} by {item.result.technician_name}. This record is immutable.</p></div>}
    </section>)}</div>
}
