import Link from 'next/link'
import { fetchAPI } from '@/lib/api'
import type { LabOrder } from '@/lib/labTypes'
import { labLabel, labStatusClass } from '@/lib/labTypes'
import LabOrderWorkflow from './LabOrderWorkflow'

export default async function LabOrderDetail({ params }: { params: { id: string } }) {
  const order = await fetchAPI(`/lab/orders/${params.id}`) as LabOrder
  return <div className="space-y-6"><div><Link href="/lab/orders" className="text-sm font-semibold text-blue-700">← Back to lab orders</Link><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold text-slate-900">Lab Order #{order.id}</h1><p className="mt-1 text-slate-600">Ordered {new Date(order.ordered_at).toLocaleString()}</p></div><div className="flex gap-2"><span className={`rounded-full px-3 py-1.5 text-sm font-semibold capitalize ring-1 ring-inset ${labStatusClass(order.priority)}`}>{order.priority}</span><span className={`rounded-full px-3 py-1.5 text-sm font-semibold capitalize ring-1 ring-inset ${labStatusClass(order.status)}`}>{labLabel(order.status)}</span></div></div></div><section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Order information</h2><dl className="mt-5 grid gap-5 md:grid-cols-3"><div><dt className="text-xs font-semibold uppercase text-slate-500">Patient</dt><dd className="mt-1 font-medium">{order.patient_name} (#{order.patient_id})</dd><dd className="text-sm text-slate-500">{order.patient_age ?? 'Age unavailable'} · {order.patient_gender || 'Gender unavailable'}</dd></div><div><dt className="text-xs font-semibold uppercase text-slate-500">Doctor</dt><dd className="mt-1 font-medium">{order.doctor_name}</dd></div><div><dt className="text-xs font-semibold uppercase text-slate-500">Appointment</dt><dd className="mt-1">{order.appointment_id ? `#${order.appointment_id}` : 'Not linked'}</dd></div><div className="md:col-span-3 rounded-xl bg-blue-50 p-4"><dt className="text-xs font-semibold uppercase text-blue-700">Instructions</dt><dd className="mt-1 whitespace-pre-line text-blue-950">{order.instructions || 'No special instructions supplied.'}</dd></div></dl></section><LabOrderWorkflow order={order}/></div>
}
