import Link from 'next/link'
import AutoRefresh from '@/components/AutoRefresh'
import { fetchAPI } from '@/lib/api'
import type { AmbulanceDashboard } from '@/lib/ambulanceTypes'

export default async function AmbulanceDashboardPage() {
  const data = await fetchAPI('/ambulance/dashboard') as AmbulanceDashboard
  const metrics = [['Available ambulances', data.available_ambulances], ['Active trips', data.active_trips], ['Pending requests', data.pending_requests], ['Assigned requests', data.assigned_requests], ['Completed trips', data.completed_trips]] as const
  return <div className="space-y-6"><AutoRefresh interval={30000}/><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm font-semibold uppercase tracking-wider text-blue-600">Emergency transport</p><h1 className="mt-1 text-3xl font-bold text-slate-900">Ambulance Staff Dashboard</h1><p className="mt-1 text-slate-600">Assigned vehicles, emergency requests, active transport, and trip completion.</p></div><div className="flex gap-2"><Link href="/ambulance/requests" className="rounded-xl bg-blue-600 px-4 py-2 font-semibold text-white">Requests</Link><Link href="/ambulance/trips" className="rounded-xl border border-slate-300 px-4 py-2 font-semibold text-slate-700">Trips</Link></div></div><div className="grid grid-cols-2 gap-4 lg:grid-cols-5">{metrics.map(([label, value]) => <section key={label} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-slate-900">{value}</p></section>)}</div><section className="rounded-2xl border border-red-100 bg-white shadow-sm"><div className="border-b border-red-100 p-5"><h2 className="text-xl font-semibold text-red-900">Emergency alerts</h2></div>{data.emergency_alerts.length === 0 ? <p className="p-6 text-slate-500">No urgent transport alert.</p> : <div className="divide-y">{data.emergency_alerts.map(item => <Link key={item.id} href={`/ambulance/requests/${item.id}`} className="flex flex-col gap-1 p-5 hover:bg-red-50 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-slate-900">Request #{item.id} · {item.patient_name || 'Unknown patient'}</p><p className="text-sm text-slate-600">{item.pickup_location} → {item.destination || 'Destination not recorded'}</p></div><span className="rounded-full bg-red-100 px-3 py-1 text-xs font-bold uppercase text-red-800">{item.status.replace('_', ' ')}</span></Link>)}</div>}</section><p className="rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm text-blue-900">Transport scope only. Clinical history, consultation, prescriptions, pharmacy, lab, radiology, billing, accounting, insurance, employee management, and hospital administration are unavailable.</p></div>
}
