'use client'
import Link from 'next/link'
import { useState } from 'react'
import { createRadiologyReportAction, finalizeRadiologyReportAction, recordImagingStudyAction, startImagingReviewAction } from '@/app/actions/radiologist'
import type { RadiologistActionResult } from '@/app/actions/radiologist'
import SubmitButton from '@/components/SubmitButton'
import type { RadiologyOrder } from '@/lib/radiologistTypes'
const field = 'mt-1 w-full rounded-xl border border-slate-300 p-3'
export default function ImagingReviewWorkflow({ order }: { order: RadiologyOrder }) {
  const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  async function run(action: (data: FormData) => Promise<RadiologistActionResult>, data: FormData, message: string) { setError(''); setNotice(''); const response = await action(data); if (response.error) setError(response.error); else setNotice(message) }
  const latest = order.reports[0]
  return <div className="space-y-4">{error && <p className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{notice && <p className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{notice}</p>}{!order.study && ['ordered','scheduled'].includes(order.status) && <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Record imaging study</h2><p className="mt-1 text-sm text-slate-600">Use the identifier/reference supplied by the supported imaging or PACS workflow.</p><form action={data => run(recordImagingStudyAction, data, 'Imaging study recorded.')} className="mt-5 grid gap-3 md:grid-cols-2"><input type="hidden" name="order_id" value={order.id}/><label className="text-sm font-medium">Study identifier<input name="study_identifier" required maxLength={150} className={field}/></label><label className="text-sm font-medium">Storage reference<input name="storage_reference" maxLength={255} placeholder="PACS/DICOM reference" className={field}/></label><div className="md:col-span-2 flex justify-end"><SubmitButton className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Record study</SubmitButton></div></form></section>}
    {order.study && order.status === 'performed' && <section className="rounded-2xl border border-blue-200 bg-blue-50 p-6"><h2 className="text-xl font-semibold text-blue-950">Start interpretation review</h2><p className="mt-1 text-sm text-blue-800">Starting review assigns this order to you and removes it from other radiologists' queues.</p><form action={data => run(startImagingReviewAction, data, 'Imaging review started.')} className="mt-4"><input type="hidden" name="order_id" value={order.id}/><SubmitButton className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Start review</SubmitButton></form></section>}
    {order.study && order.status === 'reviewing' && !latest && <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Record interpretation & create report</h2><form action={data => run(createRadiologyReportAction, data, 'Draft report created.')} className="mt-5 grid gap-3 md:grid-cols-2"><input type="hidden" name="order_id" value={order.id}/><input type="hidden" name="study_id" value={order.study.id}/><label className="text-sm font-medium md:col-span-2">Findings<textarea name="findings" rows={4} maxLength={10000} className={field}/></label><label className="text-sm font-medium md:col-span-2">Impression<textarea name="impression" rows={3} maxLength={5000} className={field}/></label><label className="text-sm font-medium">Recommendations<textarea name="recommendations" rows={2} maxLength={3000} className={field}/></label><label className="text-sm font-medium">Radiologist notes<textarea name="radiologist_notes" rows={2} maxLength={3000} className={field}/></label><div className="md:col-span-2 flex justify-end"><SubmitButton className="rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">Create draft report</SubmitButton></div></form></section>}
    {latest?.status === 'draft' && <section className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><h2 className="text-xl font-semibold text-amber-950">Draft report v{latest.version}</h2><p className="mt-2 text-sm text-amber-900">{latest.impression || 'Impression not entered yet.'}</p><div className="mt-4 flex flex-wrap gap-2"><Link href="/radiologist/reports" className="rounded-xl border border-amber-400 px-4 py-3 font-semibold text-amber-900">Edit draft</Link><form action={data => run(finalizeRadiologyReportAction, data, 'Report finalized and locked.')}><input type="hidden" name="order_id" value={order.id}/><input type="hidden" name="report_id" value={latest.id}/><SubmitButton className="rounded-xl bg-emerald-600 px-4 py-3 font-semibold text-white">Finalize report</SubmitButton></form></div></section>}
    {latest?.status === 'finalized' && <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 text-emerald-950"><h2 className="text-xl font-semibold">Finalized report v{latest.version}</h2><p className="mt-2">{latest.impression}</p><p className="mt-2 text-sm">Finalized {latest.finalized_at ? new Date(latest.finalized_at).toLocaleString() : ''}. Direct modification is blocked.</p><Link href="/radiologist/reports" className="mt-4 inline-block font-semibold text-blue-700">View report and amendment workflow</Link></section>}
  </div>
}
