import Link from 'next/link'
import { fetchAPI } from '@/lib/api'
import type { RadiologyOrder } from '@/lib/radiologistTypes'
import { imagingClass, imagingLabel } from '@/lib/radiologistTypes'
import ImagingReviewWorkflow from './ImagingReviewWorkflow'

export default async function ImagingOrderDetail({ params }: { params: { id: string } }) {
  const order = await fetchAPI(`/radiology/orders/${params.id}`) as RadiologyOrder
  return <div className="space-y-6"><div><Link href="/radiologist/orders" className="text-sm font-semibold text-blue-700">← Back to imaging orders</Link><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold text-slate-900">Imaging Order #{order.id}</h1><p className="mt-1 text-slate-600">{order.modality_name} · {order.body_part || 'Body part not specified'}</p></div><div className="flex gap-2"><span className={`rounded-full px-3 py-1.5 text-sm font-semibold capitalize ring-1 ring-inset ${imagingClass(order.priority)}`}>{order.priority}</span><span className={`rounded-full px-3 py-1.5 text-sm font-semibold capitalize ring-1 ring-inset ${imagingClass(order.status)}`}>{imagingLabel(order.status)}</span></div></div></div><section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Imaging request</h2><dl className="mt-5 grid gap-5 md:grid-cols-3"><div><dt className="text-xs font-semibold uppercase text-slate-500">Patient</dt><dd className="mt-1 font-medium">{order.patient_name} (#{order.patient_id})</dd><dd className="text-sm text-slate-500">{order.patient_age ?? 'Age unavailable'} · {order.patient_gender || 'Gender unavailable'}</dd></div><div><dt className="text-xs font-semibold uppercase text-slate-500">Ordering doctor</dt><dd className="mt-1 font-medium">{order.doctor_name}</dd></div><div><dt className="text-xs font-semibold uppercase text-slate-500">Order date</dt><dd className="mt-1">{new Date(order.ordered_at).toLocaleString()}</dd></div><div className="md:col-span-3 rounded-xl bg-blue-50 p-4"><dt className="text-xs font-semibold uppercase text-blue-700">Clinical indication</dt><dd className="mt-1 whitespace-pre-line text-blue-950">{order.clinical_indication || 'No clinical indication supplied.'}</dd></div></dl></section>{order.study && <section className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Study information</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><div><p className="text-xs font-semibold uppercase text-slate-500">Study identifier</p><p className="mt-1 font-medium">{order.study.study_identifier}</p></div><div><p className="text-xs font-semibold uppercase text-slate-500">Performed</p><p className="mt-1">{new Date(order.study.performed_at).toLocaleString()}</p></div><div><p className="text-xs font-semibold uppercase text-slate-500">Storage reference</p><p className="mt-1 break-all">{order.study.storage_reference || 'Not provided'}</p></div></div></section>}<ImagingReviewWorkflow order={order}/></div>
}
