import Link from 'next/link'
import { fetchAPI } from '@/lib/api'
import type { PharmacyPrescription } from '@/lib/pharmacistTypes'
import { pharmacyStatusClass, pharmacyStatusLabel } from '@/lib/pharmacistTypes'
import ReviewActions from './ReviewActions'

export default async function PrescriptionDetail({ params }: { params: { id: string } }) {
  const item = await fetchAPI(`/pharmacy/prescriptions/${params.id}`) as PharmacyPrescription
  return <div className="space-y-6">
    <div><Link href="/pharmacist/prescriptions" className="text-sm font-semibold text-blue-700">← Back to prescriptions</Link><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-bold text-slate-900">Prescription #{item.id}</h1><p className="mt-1 text-slate-600">Doctor-issued record · clinical fields are read-only</p></div><span className={`rounded-full px-3 py-1.5 text-sm font-semibold capitalize ring-1 ring-inset ${pharmacyStatusClass(item.pharmacy_status)}`}>{pharmacyStatusLabel(item.pharmacy_status)}</span></div></div>
    <div className="grid gap-6 lg:grid-cols-3"><section className="lg:col-span-2 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Prescription details</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><div><dt className="text-xs font-semibold uppercase text-slate-500">Patient</dt><dd className="mt-1 font-medium">{item.patient_name} (#{item.patient_id})</dd></div><div><dt className="text-xs font-semibold uppercase text-slate-500">Doctor</dt><dd className="mt-1 font-medium">{item.doctor_name}</dd></div><div><dt className="text-xs font-semibold uppercase text-slate-500">Prescription date</dt><dd className="mt-1">{new Date(item.prescription_date).toLocaleString()}</dd></div><div><dt className="text-xs font-semibold uppercase text-slate-500">Appointment</dt><dd className="mt-1">#{item.appointment_id} · {item.appointment_date}</dd></div><div className="sm:col-span-2 rounded-xl bg-blue-50 p-4"><dt className="text-xs font-semibold uppercase text-blue-700">Medicine prescribed</dt><dd className="mt-1 text-lg font-semibold text-blue-950">{item.medicine || 'Not specified'}</dd></div><div><dt className="text-xs font-semibold uppercase text-slate-500">Dosage</dt><dd className="mt-1 whitespace-pre-line">{item.dosage || 'Not specified'}</dd></div><div><dt className="text-xs font-semibold uppercase text-slate-500">Instructions</dt><dd className="mt-1 whitespace-pre-line">{item.instructions || 'No additional instructions'}</dd></div><div className="sm:col-span-2"><dt className="text-xs font-semibold uppercase text-slate-500">Diagnosis (read-only)</dt><dd className="mt-1 whitespace-pre-line text-slate-700">{item.diagnosis || 'Not provided'}</dd></div></dl></section><ReviewActions prescription={item}/></div>
  </div>
}
