const SPECIALIZATIONS = [
  'General Physician / Internal Medicine',
  'Family Medicine',
  'General Practitioner',
  'Preventive Medicine',
  'Geriatric Medicine — elderly care',
  'Adolescent Medicine',
  'Cardiologist — heart',
  'Pulmonologist / Chest Physician — lungs',
  'Gastroenterologist — digestive system',
  'Hepatologist — liver',
  'Nephrologist — kidneys',
  'Endocrinologist — hormones, diabetes, thyroid',
  'Rheumatologist — arthritis, autoimmune diseases',
  'Hematologist — blood disorders',
  'Oncologist — cancer',
  'Infectious Disease Specialist',
  'Allergist / Immunologist',
  'Clinical Geneticist',
  'Sleep Medicine Specialist',
  'Palliative Medicine Specialist',
  'Neurologist',
  'Neurosurgeon',
  'Psychiatrist',
  'Clinical Neurophysiologist',
  'Pain Medicine Specialist',
  'Addiction Medicine Specialist',
  'General Surgeon',
  'Cardiothoracic Surgeon — heart/chest surgery',
  'Vascular Surgeon — blood vessels',
  'Orthopedic Surgeon — bones/joints',
  'Plastic & Reconstructive Surgeon',
  'Colorectal Surgeon',
  'Bariatric Surgeon — weight-loss surgery',
  'Transplant Surgeon',
  'Pediatric Surgeon',
  'Trauma Surgeon',
  'Surgical Oncologist',
  'Orthopedic Doctor / Orthopedic Surgeon',
  'Sports Medicine Physician',
  'Physical Medicine & Rehabilitation Specialist / Physiatrist',
  'Rheumatologist',
  'Dermatologist',
  'Dermatologic Surgeon',
  'Cosmetic Dermatologist',
  'Hair/Trichology-focused Dermatologist',
  'Ophthalmologist — eyes',
  'ENT Specialist / Otolaryngologist — ear, nose, throat',
  'Otologist / Neurotologist — ear',
  'Rhinologist — nose/sinuses',
  'Laryngologist — voice/throat',
  'Obstetrician — pregnancy and childbirth',
  'Gynecologist',
  'OB-GYN',
  'Maternal-Fetal Medicine Specialist',
  'Reproductive Medicine / Fertility Specialist',
  'Gynecologic Oncologist',
  'Urogynecologist',
  'Pediatrician',
  'Neonatologist — newborns',
  'Pediatric Cardiologist',
  'Pediatric Neurologist',
  'Pediatric Endocrinologist',
  'Pediatric Gastroenterologist',
  'Pediatric Nephrologist',
  'Pediatric Pulmonologist',
  'Pediatric Oncologist/Hematologist',
  'Urologist',
  'Andrologist',
  'Urologic Oncologist',
  'Pediatric Urologist',
  'Reproductive Urologist',
  'Dentist',
  'Orthodontist',
  'Oral & Maxillofacial Surgeon',
  'Periodontist',
  'Endodontist',
  'Prosthodontist',
  'Pediatric Dentist',
  'Oral Medicine Specialist',
  'Oral Pathologist',
  'Radiologist',
  'Interventional Radiologist',
  'Nuclear Medicine Physician',
  'Pathologist',
  'Clinical Pathologist',
  'Anatomical Pathologist',
  'Forensic Pathologist',
  'Emergency Medicine Physician',
  'Critical Care / Intensive Care Specialist',
  'Anesthesiologist',
  'Trauma Specialist',
  'Occupational Medicine Specialist',
  'Aerospace Medicine Specialist',
  'Sports Medicine Specialist',
  'Sexual Medicine Specialist',
  'Rehabilitation Medicine Specialist',
  'Hospice & Palliative Care Specialist',
  'Medical Toxicologist',
  'Forensic Medicine Specialist',
] as const

export const DOCTOR_SPECIALIZATIONS = [...SPECIALIZATIONS].sort((first, second) =>
  first.localeCompare(second, 'en', { sensitivity: 'base' }),
)
